//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Award
    {
        public string CastName { get; set; }
        public string AwardType { get; set; }
        public string AwarderFor { get; set; }
        public string YearAwarded { get; set; }
    }
}
